version: '3.8'
services:
  ts-api-docker:
    build: .
    environment:
      PING_LISTEN_PORT: 3000
    deploy:
      replicas: 4
    volumes:
      - ./:/usr/src/app


  nginx-reverse-proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ts-api-docker