apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: tp
  name: rs
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rs
  template:
    metadata:
      labels:
        app: rs
    spec:
      containers:
      - name: api
        image: registry.cluster.wik.cloud/public/echo
        ports:
        - containerPort: 8080